public class bhaswanth {
    
        integer a;
    integer b;
    integer c;
   
    public void main(Integer p, integer q, integer r)
    {
      p=a;
        q=b;
        r=c;
        
        mul();
        add();
        sub();
        

    }
    public void mul()
    {
        integer x;
      x = a*b;
    
        system.debug('The multiplication of the variables is'  +x);
    }
    public void add()
    {
        Integer x;
        x = a+b;
        system.debug('The addition of the variables is'  +x);
    }
       public void sub()
    {
        Integer x;
        x = a-b;
        system.debug('The subtraction of the variables is'  +x);
    }    
}